# Generated by Django 3.2.8 on 2024-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
